### ISSUE TITLE
Long term: Make ROOT dependency optional

### ISSUE THREAD

**Issue by KonstantinSchubert** [scikit-hep/root_numpy#250]
I started wondering how difficult (technically and license-wise) it would be to remove the ROOT-depenency of root_numpy. 

Do you have an idea which path one would have to go in order to achieve this?
Package the needed ROOT source files with root_numpy or re-implement the root file format?

**Comment by ndawe** [comment]
Just so other readers know, @KonstantinSchubert and I have discussed this possibility and we both agree that this would be a huge benefit to users of root_numpy. This could allow a lightweight installation including at least the root2array and array2root functionality. I think copying ROOT source into root_numpy would breach ROOT's LGPL (linking against it is fine of course). I suppose dual-licensing could be an option. In the case that the user wants to use the self-contained root_numpy including ROOT source, they would accept LGPL, otherwise they would accept MIT.

**Comment by ibab** [comment]
I've experimented with producing an minimal IO-only version of ROOT in the past, but didn't make a lot of progress.
It's a very daunting task, as there are lots of cross-dependencies around the IO part of ROOT.
(For example, I didn't see how it could be possible to extract the IO part without also keeping things like the introspection code and the modified version of LLVM in the source tree).
Maybe writing a standalone library that is only capable of reading/writing TTrees from scratch would be an easier goal.

**Comment by KonstantinSchubert** [comment]
I've also heard rumors (can't remember where) that there are plans for R00T7 to crate an independent I/O nucleus of root which can be compiled independently. 

Might be interesting to ask Axel http://axel.web.cern.ch/axel/ about it. I tried to reach him in Twitter but he did not respond yet.

**Comment by ndawe** [comment]
This could potentially become a reality sooner rather than later. Watch this space...

**Comment by cbourjau** [comment]
Any news on this? Having an independent root IO package would be fantastic!

**Comment by kratsg** [comment]
> Any news on this? Having an independent root IO package would be fantastic!

It will take quite a bit of work to get this working, and I don't think we have enough manpower at the moment to make this happen sooner rather than later.

**Comment by mayou36** [comment]
Any changes on this already? I have stumbled upon this library https://github.com/scikit-hep/uproot/ which seems to achieve actually exactly this goal (with some functionality constraints currently, of course). But the goal of this library was to show how "easy" a ROOT independent root file conversion to numpy can be.

Maybe it makes sense to work together and implement a ROOT-free conversion (as an alternative "backend" for root_numpy and letting users switch for example?)

**Comment by ndawe** [comment]
@mayou36 exactly. @jpivarski what are your thoughts on this? Cythonizing uproot would make is possible to "cimport" it within root_numpy as an alternate backend.

**Comment by jpivarski** [comment]
I'm in favor of this, in fact was hoping it would happen eventually. Some of the interface root_numpy has and some users might expect, like calculating TFormulae on the fly, won't be possible because that parser is part of ROOT.

@ndawe and I were discussing by e-mail where Cython might be needed to accelerate uproot (a few isolated places, but many), but notwithstanding any performance reasons, it sounds like it would be needed just to be used as a backend. Is that right? You can't use a pure Python catch as a back-end?

**Comment by ndawe** [comment]
It should actually be possible to use a pure-Python back-end, just easiest if it's a cython module since all of root_numpy's heavy lifting is already cythonized. Another thought: we could fall back on numexpr or numba for "TFormula"-like expression evaluation if using the standalone back-end (PyTables uses numexpr).

**Comment by eduardo-rodrigues** [comment]
Closing this thread at this stage given what  [uproot](https://github.com/scikit-hep/uproot/)  is providing and the directions we are taking within the org. Seems reasonable as this task here will never be one as suggested.
