### ISSUE TITLE
joss review: warning during compilation

### ISSUE THREAD

**Issue by wlav** [scikit-hep/root_numpy#329]
Probably known already but FWIW:

In file included from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1781:0,
                 from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from root_numpy/src/_librootnumpy.cpp:449:
/usr/lib64/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \

Recommend to suppress in non-developer mode.

**Comment by ndawe** [comment]
Yes, this is the infamous deprecation warning from Cython using the deprecated numpy API:

http://docs.cython.org/en/latest/src/reference/compilation.html#configuring-the-c-build

Until Cython is released with support for the new numpy API, this warning is to be ignored.

**Comment by ndawe** [comment]
After some thought I think it's best to just leave the warning as it is. When pip installing root_numpy the user anyway doesn't see the warning unless you use pip's verbose flag. Other tools using Cython's numpy interface (scikit-learn) have the same warning and they don't make any attempt to hide it since it.
