### ISSUE TITLE
Python 3.8 Support?

### ISSUE THREAD

**Issue by adamdddave** [scikit-hep/root_numpy#395]
Dear root_numpy gurus:
Thanks very much for the package! Question: Will there be support for python 3.8 in the near future? I've tried both `pip install` and `git clone` and running `setup.py`, which both seem to fail on line 40 of `setup.py`, which seems very similar to an issue in matplotlib (https://github.com/matplotlib/matplotlib/issues/14580). Is there any chance of extending support?

For more info, I'm trying to set up using conda-forge, and have in the environment

Python 3.8.0 | packaged by conda-forge | (default, Nov  6 2019, 23:20:36) 

Thanks!!

**Comment by kratsg** [comment]
No. Please use [uproot](https://github.com/scikit-hep/uproot).

**Comment by eduardo-rodrigues** [comment]
Slightly more details explanation: @adamdddave, the issue is that support is not for free and uproot has effectively superseded root_numpy in the past year or so. It's also increasingly more difficult to keep up with the evolution of the stack dependencies for all major platforms. It's just a fact that uproot is way lighter and better. We will archive root_numpy in 2020 and should be soon putting a warning on the README ...

Now, if you miss some functionality in uproot (and awkward-array), then please file a feature request / issue in there, so that the overall ecosystem improves.

I hope you understand the issues. Thanks.

**Comment by adamdddave** [comment]
Makes sense. It may be worth it to add a deprecation warning then, so that other packages (looking at root_pandas) and anything else which calls it under the hood can see it trivially.

**Comment by eduardo-rodrigues** [comment]
Fair point, Adam. I will try and update the READMEs of root_numpy and root_pandas this week ...
