### ISSUE TITLE
Incompatible with ROOT version 6.20.00

### ISSUE THREAD

**Issue by VukanJ** [scikit-hep/root_numpy#400]
conda is unable to install ROOT version 6.20.00 with root_pandas which is probably due to a root_numpy dependency which can not be resolved. (Is it going to be resolved?) Given that uproot does not yet support updating a TFile (Adding branches to an existing file for example) and a straight forward method for simply writing pandas DataFrames to a root file, isn't it a bit too early to deprecate root_numpy and its dependents?

**Comment by chrisburr** [comment]
This is actually a root_numpy problem so I've moved the issue over. Assuming root_numpy isn't incompatible with the new ROOT it will be fixed in the next few days by https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/410

Be aware though that `root_numpy` is unmaintained (see [here](https://github.com/scikit-hep/root_numpy#warningroot_numpy-is-deprecated-and-unmaintainedwarning) for details and alternatives). It will probably keep working but there are already known issues with newer ROOT versions and this list will only grow with time.

**Comment by VukanJ** [comment]
Ok, thank you for the info! I hope that uproot is going to support updating TFiles before root_numpy/root_pandas finally stop working. There is no package that I am aware of that can do that other that root_pandas

**Comment by chrisburr** [comment]
This should be fixed now

**Comment by eduardo-rodrigues** [comment]
Hi. Well, `root_numpy` isn't quite up-to-date, see for example https://github.com/scikit-hep/root_numpy/pull/389. Since you are a user @VukanJ, would you try and contribute to this package to update it while the package is needed? In the end we are a community of folks and there's only that much one can do, so users becoming developers is the way to achieve sustainability. It would be great if you could contribute to this and `root_pandas` where relevant, even if just a little bit. Thanks!

**Comment by VukanJ** [comment]
Since this root_numpy is working again with conda-forge (thanks @chrisburr for the update) there is no urgent need to improve root_numpy/root_pandas any more, as it will/should be superseded by uproot. After all, root_numpy is deprecated. If I decide to contribute to a project, it would be uproot because there some important features are missing, but for now I am happy that I can continue my work as usual.

**Comment by eduardo-rodrigues** [comment]
Sure. I was expecting that comment. There are other issues coming up every now and then, but I do agree that missing functionality in uproot should rather be the focus. Thanks @VukanJ.
