### ISSUE TITLE
OSError when using root2array

### ISSUE THREAD

**Issue by AnirudhDagar** [scikit-hep/root_numpy#401]
Hi, I'm trying to load a root file tree into a NumPy array using the `root2array`.

```python
arr = root2array('/Users/gollum/Downloads/Higgs_data.root', treename='sig_tree;1')
```

I can get this to work on Python 3.7.7 with root_numpy installed and rootpy(ROOT 6.20/02) installed using pip.

But when I run the same code for Python 3.7.7 with ROOT(6.21/01) compiled and built from source, I face this issue.

I get into the following error:
---------------------------------------------------------------------------
```
OSError                                   Traceback (most recent call last)
<ipython-input-20-8481e6693760> in <module>
----> 1 arr = root2array('/Users/gollum/Downloads/Higgs_data.root', treename='sig_tree;1')

/usr/local/lib/python3.7/site-packages/root_numpy/_tree.py in root2array(filenames, treename, branches, selection, object_selection, start, stop, step, include_weight, weight_name, cache_size, warn_missing_tree)
    239         weight_name,
    240         cache_size,
--> 241         warn_missing_tree)
    242 
    243     if flatten:

root_numpy/src/tree.pyx in _librootnumpy.root2array_fromfile()

OSError: unable to access tree 'sig_tree;1' in /Users/gollum/Downloads/Higgs_data.root
```

```
Error in <TTreePlayer::UnbinnedFit>: Unknown function: /Users/gollum/Downloads/Higgs_data.root
```

**Comment by eduardo-rodrigues** [comment]
Hello @AnirudhDagar, irrespective of the error: it seems you are doing nothing fancy and I would really urge you to use `https://github.com/scikit-hep/uproot` that has superseded `root_numpy`. As you can see from the README the latter is deprecated and we are no longer developing this package since `uproot` is better is many ways; in particular, a simple `pip install` or `conda install` makes it as easy as it gets - no compilation.

Let us know how you get along. Thanks for using Scikit-HEP stuff!

**Comment by AnirudhDagar** [comment]
Sure! It's a small problem, and I just wanted to report the issue. For now, I've got around the problem but will see the uproot documentation for loading in a root file and extracting a NumPy array from the file in the future.

Thanks a lot! :)
