### ISSUE TITLE
feature request: array2hist compatible with THnSparse

### ISSUE THREAD

**Issue by nrad** [scikit-hep/root_numpy#403]
Is there a technical reason why hist2array is compatible with THnSparse, but array2hist is not?

**Comment by eduardo-rodrigues** [comment]
Hi. Probably largely because nobody required the functionality ...

You're probably seen that this package has been deprecated since a while since unmaintained and superseded by https://github.com/scikit-hep/uproot4, https://github.com/scikit-hep/awkward-1.0, and other histogramming tools such as https://github.com/scikit-hep/boost-histogram. If you have specific needs I would really encourage you to get in touch via one of these repositories ... Even better if you join the gang and commit some code :-).

I'm hence closing this issue.
