### ISSUE TITLE
sudo install does not guarantee to have ROOTSYS set

### ISSUE THREAD

**Issue by johannct** [scikit-hep/root_numpy#97]
When building the package, one needs ROOTSYS to be set. The problem is that when doing sudo python setup.py install, ROOTSYS is not preserved by sudo, and so I get : 
cohen@arago:~/sources/python/root_numpy$ sudo python setup.py install
Traceback (most recent call last):
  File "setup.py", line 45, in <module>
    "root-config is not in PATH and ROOTSYS is not set. "
RuntimeError: root-config is not in PATH and ROOTSYS is not set. Is ROOT installed and setup properly?
cohen@arago:~/sources/python/root_numpy$ which root-config
/home/cohen/sources/root-svn/bin/root-config
cohen@arago:~/sources/python/root_numpy$ echo $ROOTSYS
/home/cohen/sources/root-svn

I am surprised that I did not have this problem with other python packages though

**Comment by irinapiazza** [comment]
The problem is that you are not set the ROOTSYS enviroment variable. So I suggest write like that in your terminal:
export ROOTSYS=PATH
PATH= path where you put in your root folder (for me is: export ROOTSYS=/home/ubuntu/Downloads/root-6.04.02/)

then copy and save this comande to .bashrc hidden file to get  permanent variable.
And try to install only after that with

sudo ROOTSYS=$ROOTSYS python setup.py install
